import type { Metadata } from 'next';
import './globals.css';
import { FollowerSideBar, Sidebar } from '@/components/sidebar';
import { Toaster } from 'react-hot-toast';
import { Rubik } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Social APP',
  description: 'Generated by create next app',
};

const rubikFont = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${rubikFont.className}`}>
        <Toaster />
        <main className="flex">
          <Sidebar />
          <div className="flex-1">{children}</div>
          <FollowerSideBar />
        </main>
      </body>
    </html>
  );
}
