import type { Metadata } from 'next';
import './globals.css';
import { FollowerSideBar, Sidebar } from '@/components/sidebar';

export const metadata: Metadata = {
  title: 'Social APP',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main className="flex">
          <Sidebar />
          <div className="flex-1 ml-5 min-h-screen pt-5 mr-5">{children}</div>
          <FollowerSideBar />
        </main>
      </body>
    </html>
  );
}
